;Aliases that are required to work with dev version of Test Vue
;copy and paste these aliases into webaliases.ini

[Alias]

; Test Vue
/test-vue-dev/=C:\GitHub\plugins\dev-web-plugin-examples\TestVue\
/test-vue-dev/index.html=C:\GitHub\plugins\dev-web-plugin-examples\TestVue\index.html
/test-vue-build/=C:\GitHub\plugins\dev-web-plugin-examples\TestVue\dist\
/test-vue-build/index.html=C:\GitHub\plugins\dev-web-plugin-examples\TestVue\dist\index.html
/mainTestVue.js=C:\GitHub\plugins\dev-web-plugin-examples\TestVue\dist\mainTestVue.js
